### PR TITLE
alias _id not added correctly

### PR DESCRIPTION
**Pull request by javicalle**
Aliases for sensor not added correctly
And some debug traces.

(I apologize in advance, I'm not familiar with how Github works)

### CODE REVIEW

**Comment by emontnemery** [comment]
Thanks!
I removed the extra debug traces though.

**Comment by emontnemery** [comment]
You need to sign the home-assistant cla also by the way: https://github.com/home-assistant/home-assistant/pull/17402#issuecomment-429608168

**Comment by javicalle** [comment]
> You need to sign the home-assistant cla also by the way: [home-assistant#17402 (comment)](https://github.com/home-assistant/home-assistant/pull/17402#issuecomment-429608168)

Done.

A little question, why there are few traces in the code?
Do not get me wrong, it's not a complaint at all, but I'm a big fan of putting traces in code and in general I find too few in HA.
It is some kind of convention or rule about it?

**Comment by emontnemery** [comment]
I don't know, I didn't write the RFLink code and I'm new to home-assistant :)
In the documentation, it's suggested to use py-charm to debug home-assistant, maybe that's the preferred debug method instead of adding a lot of traces?

**Pull request merged**
